site_name: superqt
site_url: https://github.com/pyapp-kit/superqt
site_description: >-
  missing widgets and components for PyQt/PySide
# Repository
repo_name: pyapp-kit/superqt
repo_url: https://github.com/pyapp-kit/superqt

# Copyright
copyright: Copyright &copy; 2021 - 2022

watch:
  - src

theme:
  name: material
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.expand
    # - navigation.tracking
    # - navigation.tabs
    - search.highlight
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: "#"


plugins:
  - search
  - autorefs
  - macros:
      module_name: docs/_macros
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://cmap-docs.readthedocs.io/en/latest/objects.inv
          options:
              show_source: false
              docstring_style: numpy
              show_root_toc_entry: True
              show_root_heading: True
